name: Reusable Job 1

# This workflow can be called from other workflows
on:
  workflow_call:
    # You might not need inputs here if the job is self-contained.
    # But if jobs need dynamic parameters, define them here.
    # For this scenario, we just need to be able to call it.
    inputs:
      message:
        required: false
        type: string
        default: 'Hello from Job 1!'

jobs:
  run-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Execute Job 1 Logic
        run: |
          echo "Running Job 1 with message: ${{ inputs.message }}"
          # Add your actual job 1 commands here