name: Run Selected Jobs

on:
  workflow_dispatch:
    inputs:
      jobs_to_run:
        description: 'Comma-separated list of jobs to run (e.g. job1,job3)'
        required: true
        default: 'job1'

jobs:
  dynamic-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobname: [job1, job2, job3, job4, job5]

    # Only run this job if the current matrix jobname is in the input string
    if: contains(github.event.inputs.jobs_to_run, matrix.jobname)

    name: Run ${{ matrix.jobname }}
    steps:
      - name: Execute selected job
        run: echo "Running ${{ matrix.jobname }}"
