name: Run Selected Jobs

on:
  workflow_dispatch:
    inputs:
      jobs_to_run:
        description: 'Comma-separated list of jobs to run (e.g. job1,job3)'
        required: true
        default: 'job1'

jobs:
  dynamic-jobs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jobname: [job1]

    if: contains(github.event.inputs.jobs_to_run, matrix.jobname)

    name: Run ${{ matrix.jobname }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script for ${{ matrix.jobname }}
        run: |
          chmod +x ./scripts/${{ matrix.jobname }}.sh
          ./scripts/${{ matrix.jobname }}.sh
