name: Print commit SHAs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  show-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (fetch at least 2 commits)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to access previous commit

      - name: Show current and previous commit SHAs
        run: |
          echo "Current commit: $GITHUB_SHA"
          PREV_SHA=$(git rev-parse HEAD^)
          echo "Previous commit: $PREV_SHA"
