name: Developer Controlled Jobs

on:
  workflow_dispatch:
    inputs:
      developer:
        description: 'Developer name (e.g., Dev1, Dev2)'
        required: true
        default: Dev1

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read job-config.yml for developer
        id: set
        run: |
          DEV="${{ github.event.inputs.developer }}"
          JOBS=$(yq e -o=json ".\"$DEV\"" job-config.yml)
          echo "matrix={\"job\": $JOBS}" >> $GITHUB_OUTPUT

  run-jobs:
    needs: read-config
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      matrix: ${{ needs.read-config.outputs.matrix }}