name: Print commit SHAs

on:
  workflow_dispatch:

jobs:
  show-shas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (fetch at least 2 commits)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to access previous commit

      - name: Show current and previous commit SHAs
        run: |
          echo "Current commit: $GITHUB_SHA"
          PREV_SHA=$(git rev-parse HEAD^)
          echo "Previous commit: $PREV_SHA"

      - name: Force reset to previous commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          PREV_SHA=$(git rev-parse HEAD^)
          git reset --hard $PREV_SHA
          git push origin HEAD --force
