name: Print environment and repo secrets

on: [push]

jobs:
  show-vars:
    runs-on: ubuntu-latest
    environment: production  # This links the job to the 'production' environment
    steps:
      - name: Print environment variable VAR_1 and repository variable VAR_2
        run: |
          echo "VAR_1 from environment: ${{ vars.VAR_1 }}"
          echo "VAR_2 from repository: ${{ vars.var2 }}"
