name: Developer Controlled Jobs

on:
  workflow_dispatch:
    inputs:
      developer:
        description: 'Developer name (e.g., Dev1, Dev2)'
        required: true
        default: Dev1

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      job1: ${{ steps.set.outputs.job1 }}
      job2: ${{ steps.set.outputs.job2 }}
      job3: ${{ steps.set.outputs.job3 }}
      job4: ${{ steps.set.outputs.job4 }}
      job5: ${{ steps.set.outputs.job5 }}
    steps:
      - uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Parse job-config.yml
        id: set
        run: |
          DEV="${{ github.event.inputs.developer }}"
          JOBS=$(yq e ".${DEV}[]" job-config.yml)

          for JOB in job1 job2 job3 job4 job5; do
            if echo "$JOBS" | grep -q "$JOB"; then
              echo "$JOB=true" >> $GITHUB_OUTPUT
            else
              echo "$JOB=false" >> $GITHUB_OUTPUT
            fi
          done

  job1:
    needs: read-config
    if: ${{ needs.read-config.outputs.job1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job1"

  job2:
    needs: read-config
    if: ${{ needs.read-config.outputs.job2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job2"

  job3:
    needs: read-config
    if: ${{ needs.read-config.outputs.job3 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job3"

  job4:
    needs: read-config
    if: ${{ needs.read-config.outputs.job4 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job4"

  job5:
    needs: read-config
    if: ${{ needs.read-config.outputs.job5 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job5"
