name: Rollback

on:
  workflow_dispatch:

permissions:
  contents: write  # <-- This allows git push with GITHUB_TOKEN
  workflows: write

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with write access
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rollback code (preserve workflows)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          PREV_SHA=$(git rev-parse HEAD^)
          git reset --hard $PREV_SHA
          # restore workflow files from previous HEAD so they're not modified
          git restore --source=HEAD@{1} .github/workflows/
          git add .
          git commit -m "Rollback to $PREV_SHA (keeping workflows)"
          git push origin HEAD --force
